DROP TABLE IF EXISTS CAR;

CREATE SEQUENCE group_seq;
  
CREATE TABLE CAR (
  id BIGINT  default group_seq.nextval PRIMARY KEY,
  brand VARCHAR(250) NOT NULL,
  model VARCHAR(250) NOT NULL,
  color VARCHAR(250) NOT NULL,
  price INT NOT NULL,
  year INT NOT NULL
  );
